#############################################################################
# Makefile for building: OpticalNetSimulator
# Generated by qmake (2.01a) (Qt 4.7.0) on: mar jul 5 11:52:29 2011
# Project:  OpticalNetSimulator.pro
# Template: app
# Command: /opt/qtsdk-2010.05/qt/bin/qmake -spec /opt/qtsdk-2010.05/qt/mkspecs/linux-g++ CONFIG+=debug -o Makefile OpticalNetSimulator.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -w -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -w -D_REENTRANT $(DEFINES)
INCPATH       = -I/opt/qtsdk-2010.05/qt/mkspecs/linux-g++ -I. -I/opt/qtsdk-2010.05/qt/include/QtCore -I/opt/qtsdk-2010.05/qt/include/QtGui -I/opt/qtsdk-2010.05/qt/include -I. -I/usr/local/Library/aleph -I. -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/qtsdk-2010.05/qt/lib
LIBS          = $(SUBLIBS)  -L/opt/qtsdk-2010.05/qt/lib -L/usr/local/Library/aleph -lAleph -lnana -lc -lgsl -lgslcblas -lgmp -lmpfr -lasprintf -lQtGui -L/opt/qtsdk-2010.05/qt/lib -L/usr/X11R6/lib -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qtsdk-2010.05/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = test.C \
		grid_window.C \
		grid_panel.C \
		simulator.C \
		statistics_per_element.C \
		statistics.C moc_grid_window.cpp \
		moc_grid_panel.cpp
OBJECTS       = test.o \
		grid_window.o \
		grid_panel.o \
		simulator.o \
		statistics_per_element.o \
		statistics.o \
		moc_grid_window.o \
		moc_grid_panel.o
DIST          = /opt/qtsdk-2010.05/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2010.05/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2010.05/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2010.05/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		/opt/qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/warn_off.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf \
		OpticalNetSimulator.pro
QMAKE_TARGET  = OpticalNetSimulator
DESTDIR       = 
TARGET        = OpticalNetSimulator

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_grid_form.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: OpticalNetSimulator.pro  /opt/qtsdk-2010.05/qt/mkspecs/linux-g++/qmake.conf /opt/qtsdk-2010.05/qt/mkspecs/common/g++.conf \
		/opt/qtsdk-2010.05/qt/mkspecs/common/unix.conf \
		/opt/qtsdk-2010.05/qt/mkspecs/common/linux.conf \
		/opt/qtsdk-2010.05/qt/mkspecs/qconfig.pri \
		/opt/qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri \
		/opt/qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/qt_config.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/default_pre.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/debug.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/default_post.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/warn_off.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/qt.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/moc.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/resources.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/uic.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/yacc.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/lex.prf \
		/opt/qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf \
		/opt/qtsdk-2010.05/qt/lib/libQtGui.prl \
		/opt/qtsdk-2010.05/qt/lib/libQtCore.prl
	$(QMAKE) -spec /opt/qtsdk-2010.05/qt/mkspecs/linux-g++ CONFIG+=debug -o Makefile OpticalNetSimulator.pro
/opt/qtsdk-2010.05/qt/mkspecs/common/g++.conf:
/opt/qtsdk-2010.05/qt/mkspecs/common/unix.conf:
/opt/qtsdk-2010.05/qt/mkspecs/common/linux.conf:
/opt/qtsdk-2010.05/qt/mkspecs/qconfig.pri:
/opt/qtsdk-2010.05/qt/mkspecs/modules/qt_webkit_version.pri:
/opt/qtsdk-2010.05/qt/mkspecs/features/qt_functions.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/qt_config.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/exclusive_builds.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/default_pre.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/debug.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/default_post.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/warn_off.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/qt.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/unix/thread.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/moc.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/resources.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/uic.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/yacc.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/lex.prf:
/opt/qtsdk-2010.05/qt/mkspecs/features/include_source_dir.prf:
/opt/qtsdk-2010.05/qt/lib/libQtGui.prl:
/opt/qtsdk-2010.05/qt/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /opt/qtsdk-2010.05/qt/mkspecs/linux-g++ CONFIG+=debug -o Makefile OpticalNetSimulator.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/OpticalNetSimulator1.0.0 || $(MKDIR) .tmp/OpticalNetSimulator1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/OpticalNetSimulator1.0.0/ && $(COPY_FILE) --parents grid.H misc.H package.H grid_window.H grid_panel.H grid_panel_listener.H minimum_deflecting.H simulator.H sim_listener.H statistics_per_element.H statistics.H .tmp/OpticalNetSimulator1.0.0/ && $(COPY_FILE) --parents test.C grid_window.C grid_panel.C simulator.C statistics_per_element.C statistics.C .tmp/OpticalNetSimulator1.0.0/ && $(COPY_FILE) --parents grid_form.ui .tmp/OpticalNetSimulator1.0.0/ && (cd `dirname .tmp/OpticalNetSimulator1.0.0` && $(TAR) OpticalNetSimulator1.0.0.tar OpticalNetSimulator1.0.0 && $(COMPRESS) OpticalNetSimulator1.0.0.tar) && $(MOVE) `dirname .tmp/OpticalNetSimulator1.0.0`/OpticalNetSimulator1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/OpticalNetSimulator1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_grid_window.cpp moc_grid_panel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_grid_window.cpp moc_grid_panel.cpp
moc_grid_window.cpp: ui_grid_form.h \
		grid_panel.H \
		simulator.H \
		grid.H \
		tpl_euclidian_graph.H \
		package.H \
		misc.H \
		minimum_deflecting.H \
		statistics.H \
		statistics_per_element.H \
		sim_listener.H \
		grid_panel_listener.H \
		grid_window.H
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) grid_window.H -o moc_grid_window.cpp

moc_grid_panel.cpp: simulator.H \
		grid.H \
		tpl_euclidian_graph.H \
		package.H \
		misc.H \
		minimum_deflecting.H \
		statistics.H \
		statistics_per_element.H \
		sim_listener.H \
		grid_panel_listener.H \
		grid_panel.H
	/opt/qtsdk-2010.05/qt/bin/moc $(DEFINES) $(INCPATH) grid_panel.H -o moc_grid_panel.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_grid_form.h
compiler_uic_clean:
	-$(DEL_FILE) ui_grid_form.h
ui_grid_form.h: grid_form.ui
	/opt/qtsdk-2010.05/qt/bin/uic grid_form.ui -o ui_grid_form.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

test.o: test.C grid_window.H \
		ui_grid_form.h \
		grid_panel.H \
		simulator.H \
		grid.H \
		tpl_euclidian_graph.H \
		package.H \
		misc.H \
		minimum_deflecting.H \
		statistics.H \
		statistics_per_element.H \
		sim_listener.H \
		grid_panel_listener.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o test.o test.C

grid_window.o: grid_window.C grid_window.H \
		ui_grid_form.h \
		grid_panel.H \
		simulator.H \
		grid.H \
		tpl_euclidian_graph.H \
		package.H \
		misc.H \
		minimum_deflecting.H \
		statistics.H \
		statistics_per_element.H \
		sim_listener.H \
		grid_panel_listener.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grid_window.o grid_window.C

grid_panel.o: grid_panel.C grid_panel.H \
		simulator.H \
		grid.H \
		tpl_euclidian_graph.H \
		package.H \
		misc.H \
		minimum_deflecting.H \
		statistics.H \
		statistics_per_element.H \
		sim_listener.H \
		grid_panel_listener.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grid_panel.o grid_panel.C

simulator.o: simulator.C simulator.H \
		grid.H \
		tpl_euclidian_graph.H \
		package.H \
		misc.H \
		minimum_deflecting.H \
		statistics.H \
		statistics_per_element.H \
		sim_listener.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o simulator.o simulator.C

statistics_per_element.o: statistics_per_element.C statistics_per_element.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statistics_per_element.o statistics_per_element.C

statistics.o: statistics.C statistics.H \
		statistics_per_element.H
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o statistics.o statistics.C

moc_grid_window.o: moc_grid_window.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_grid_window.o moc_grid_window.cpp

moc_grid_panel.o: moc_grid_panel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_grid_panel.o moc_grid_panel.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

